config/routes.rb
Rails.application.routes.draw do
  #resources :breast_feedings
  #resources :babies
  resources :babies do
    resources :breast_feedings
  end
  root 'babies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby.rb
class Baby < ApplicationRecord
    has_many :breast_feedings, dependent: :destroy

    accepts_nested_attributes_for :breast_feedings, allow_destroy: true, reject_if: proc { |attributes| attributes['duration'].blank? }

    def to_s
      name
    end
    #total que ha bebido
    def total_drinking
      breast_feedings.sum(:quantity)
    end
    #tiempo total
    def total_duration
        breast_feedings.sum(:duration)
    end

    # Cantidad de veces que el bebe tomo hoy hasta ahora
    def breast_feeding_times_today
        breast_feedings.where("created_at >= :start_at AND created_at <= :end_date", {start_at: Time.now.beginning_of_day, end_date: Time.now}).count
    end

    # La fecha de la ultima vez que se alimento
    def last_time_drinking
        if breast_feedings.count > 0
            breast_feedings.last.created_at
        else
            ''
        end
    end

    # Cuanto tiempo ha tomado hoy
    def breast_feeding_duration_today
        breast_feedings.where("created_at >= :start_at AND created_at <= :end_date", {start_at: Time.now.beginning_of_day, end_date: Time.now}).sum(:duration)
    end

    # Cantidad de leche que ha tomado hoy
    def breast_feeding_quantity_today
        breast_feedings.where("created_at >= :start_at AND created_at <= :end_date", {start_at: Time.now.beginning_of_day, end_date: Time.now}).sum(:quantity)
    end
end

app/models/breast_feeding.rb
class BreastFeeding < ApplicationRecord
  belongs_to :baby
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  #before_action :set_baby, only: [:show, :edit, :update, :destroy]

  # GET /babies
  # GET /babies.json
  def index
    @babies = Baby.all
  end

  # GET /babies/1
  # GET /babies/1.json
  def show
    @baby = Baby.find params[:id]
  end

  # GET /babies/new
  def new
    @baby = Baby.new
    #3.times {@building.apartments.build}
    @baby.breast_feedings.build
    # Esto crea una nueva instancia de Baby y 1 instancias de Breast_feedings que pertenecen al Baby.
  end

  # GET /babies/1/edit
  def edit
    @baby = Baby.find params[:id]
  end

  # POST /babies
  # POST /babies.json
  def create
    @baby = Baby.new(baby_params)
    if @baby.save
     redirect_to baby_path(@baby)
    else
     render ‘new’
    end
  end

  # PATCH/PUT /babies/1
  # PATCH/PUT /babies/1.json
  def update
    @baby = Baby.find params[:id]
    respond_to do |format|
      if @baby.update_attributes(baby_params)
        format.html { redirect_to baby_path(@baby), notice: 'Bebe se actualizo correctamente.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /babies/1
  # DELETE /babies/1.json
  def destroy
    @baby = Baby.find params[:id]
    @baby.destroy
    respond_to do |format|
      format.html { redirect_to babies_url, notice: 'Bebe fue Destruido correctamente.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_baby
    #  @baby = Baby.find(params[:id])
    #end

    # Only allow a list of trusted parameters through.
    def baby_params
      # Esto permite que los atributos de amamantamiento sean guardados.
      # El parametró destroy  nos permite eliminar un amamantmiento cuando se enviar el formulario.
      params.require(:baby).permit(:name, :photo, apartments_attributes: [:id, :duration, :quantity, :_destroy])
    end
end

app/controllers/breast_feedings_controller.rb
class BreastFeedingsController < ApplicationController
  #before_action :set_breast_feeding, only: [:show, :edit, :update, :destroy]
  before_action :find_baby

  # GET /breast_feedings
  # GET /breast_feedings.json
  def index
    @breast_feedings = @baby.breast_feedings# Se muestran los amamantamientos asociados a este bebe
  end

  # GET /breast_feedings/1
  # GET /breast_feedings/1.json
  def show
    @breast_feeding = BreastFeeding.find(params[:id])
  end

  # GET /breast_feedings/new
  def new
    @breast_feeding = BreastFeeding.new
  end

  # GET /breast_feedings/1/edit
  def edit
    @breast_feeding = BreastFeeding.find(params[:id])
  end

  # POST /breast_feedings
  # POST /breast_feedings.json
  def create
    @breast_feeding = BreastFeeding.new(breast_feeding_params)#Strong parameters, previene ataques de mass assignment
    @breast_feeding.baby = @baby #Asignamos el bebe, ya no es necesario pasarlo en el formulario, ahora viene en la url
    respond_to do |format|
      if @breast_feeding.save
        #format.html { redirect_to baby_breast_feeding_path(@baby, @breast_feeding), notice: 'Amamantamiento fue Creado correctamente.' }
        format.html { redirect_to  baby_path(@baby), notice: 'Amamantamiento fue Creado correctamente.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /breast_feedings/1
  # PATCH/PUT /breast_feedings/1.json
  def update
    @breast_feeding = BreastFeeding.find params[:id]
    respond_to do |format|
      if @breast_feeding.update(breast_feeding_params.merge(baby: @baby))# Se añade el beb que se obtuvo en la llamada a find_baby
        format.html { redirect_to baby_path(@baby), notice: 'Amamantamiento fue Actualizado.-' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /breast_feedings/1
  # DELETE /breast_feedings/1.json
  def destroy
    @breast_feeding = BreastFeeding.find params[:id]
    @breast_feeding.destroy
    respond_to do |format| 
      #format.html { redirect_to baby_breast_feedings_url, notice: 'Amamantamiento fue Eliminado correctamente.' }
      format.html { redirect_to baby_path(@baby), notice: 'Amamantamiento fue Eliminado correctamente.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_breast_feeding
    #  @breast_feeding = BreastFeeding.find(params[:id])
    #end

    # Only allow a list of trusted parameters through.
    #def breast_feeding_params
    #  params.require(:breast_feeding).permit(:duration, :quantity, :baby_id)
    #end

    def breast_feeding_params
      params.require(:breast_feeding).permit(:duration, :quantity)
    end
  
    def find_baby
      @baby = Baby.find params[:baby_id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/helpers/breast_feedings_helper.rb
module BreastFeedingsHelper
end

app/views/babies/_form.html.erb
<%= form_with(model: baby, local: true) do |form| %>
  <% if baby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(baby.errors.count, "error") %> prohibited this baby from being saved:</h2>

      <ul>
      <% baby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-center">
    <div class="field">
    <%= form.label :name, class:" text-white", style:"font-size:15px; text-shadow: 0.1em 0.1em 0.05em #333" %>
    <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :photo, class:" text-white", style:"font-size:15px; text-shadow: 0.1em 0.1em 0.05em #333" %>
      <%= form.text_area :photo %>
    </div>

    <div class="actions mt-4">
      <%= form.submit class:"btn btn-primary rounded-pill border border-white"%>
    </div>
  </div>
  
<% end %>

app/views/babies/edit.html.erb
<div class="container">
    <div class="container-fluid p-4 shadow-lg mb-2 border border-info rounded-pill" style="background:#84c760;">
        <h1 class="text-center text-white mb-3"  style="font-size:25px; text-shadow: 0.1em 0.1em 0.05em #333">Editando Bebe</h1>
        <div class="m-3">
            <%= render 'form', baby: @baby %>
        </div>
    </div>
   
    <div class="text-center m-5">
        <%= link_to 'Ver', @baby, class:"btn btn-dark rounded-pill border border-white btn-sm"%> |
        <%= link_to 'Home', babies_path, class:"btn btn-dark rounded-pill border border-white btn-sm" %>    
    </div>    
</div>

app/views/babies/index.html.erb
<div class="container-fluid mb-5">
  
  <% if notice.present? %>
    <div class="container mx-5 mb-4 px-5 text-center">
      <div class="shadow-lg mx-5  alert alert-warning alert-dismissible fade show border border-info rounded-pill" role="alert" style="background:#d5e4a1;">
        <strong>ATENCION!</strong> <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <% end %>    

  <h1 class="text-center" style="text-shadow: 0 0 0.2em #F87, 0 0 0.2em #F87">Bebes Nahasapeemapetilon</h1>
  <br>
  <div class="row">
    <div class="col-2">
    <%= image_tag 'https://i.pinimg.com/originals/a7/e5/62/a7e5629581c59f01409f9d832ad45f71.png', class: '', style: 'width: 250px;' %>
    </div>
    <div class="col-2">
    <%= image_tag 'https://vignette.wikia.nocookie.net/simpsons/images/2/28/Manjula_Nahasapeemapetilon.png/revision/latest?cb=20181212120358&path-prefix=fr', class: '', style: 'width: 250px;' %>
    </div>
    <div class="col-6">
      <table>
        <thead>
          <tr class="border-bottom border-info"> 
          <th colspan="1"></th>
            <th class="text-center">Nombre</th>
            <th class="text-center">&nbsp;&nbsp;&nbsp;Total de Leche<br> Tomada<br> en la vida</th>
            <th class="text-center">&nbsp;&nbsp;&nbsp;Total de Tiempo<br> Ocupado<br> en la vida</th>
            <th colspan="3"></th>            
          </tr>
        </thead>
        
        <tbody>
          <% @babies.each do |baby| %>
            <tr class="border-bottom border-info">
              <td><%= image_tag baby.photo, class: 'image-fluid', style: 'width: 60px;' %></td>
              <td class="text-center"><%= baby.name %></td>
              <td class="text-center"><%= baby.total_drinking %></td>
              <td class="text-center"><%= baby.total_duration %></td>
              <td><%= link_to 'Ver', baby_path(baby), class:"btn btn-primary rounded-pill"  %></td>              
              <td><%= link_to 'Eliminar', baby_path(baby), method: :delete, data: { confirm: 'Esta Seguro?' }, class:"btn btn-danger rounded-pill" %></td>
            </tr>            
          <% end %>
        </tbody>
      </table>      
    </div>
    <div class="col-1">
        <%= link_to 'Nuevo bebe', new_baby_path(@baby), class:"shadow-lg p-3 mb-5 text-center btn btn-secondary rounded-circle border border-white ", style:"box-shadow: 60px -16px teal;" %>
    </div>
  </div>
<div>

app/views/babies/new.html.erb
<div class="container">
    <div class="container-fluid p-4 shadow-lg mb-2 border border-info rounded-pill" style="background:#84c760;">
        <h1 class="text-center text-white mb-3"  style="font-size:25px; text-shadow: 0.1em 0.1em 0.05em #333">Nuevo Bebe</h1>
        <div class="m-3">
            <%= render 'form', baby: @baby %>
        </div>
    </div>
   
    <div class="text-center m-5">
        <%= link_to 'Home', babies_path, class:"btn btn-dark rounded-pill border border-white btn-sm" %>    
    </div>    
</div>

app/views/babies/show.html.erb
<div class="text-center px-5">
  
   <% if notice.present? %>
    <div class="container mx-5 mb-4 px-5 text-center">
      <div class="shadow-lg mx-5  alert alert-warning alert-dismissible fade show border border-info rounded-pill" role="alert" style="background:#d5e4a1;">
        <strong>ATENCION!</strong> <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <% end %>    

  <div class="container-fluid pt-2 shadow-lg mb-2 border border-info rounded-pill" style="background:#84c760;">
    <h1 class="text-center text-white mb-3"  style="font-size:25px; text-shadow: 0.1em 0.1em 0.05em #333">Informacion de Lactancia del Bebe <%= image_tag 'pngwing.png', style:"width:70px;" %></h1>
    <div class="row pb-4">
      <div class="col-2 ml-3 pl-3">
        <%= image_tag @baby.photo, style:"width:100px;" %>
        <p class=" text-white" style="font-size:15px; text-shadow: 0.1em 0.1em 0.05em #333">
          <strong>Nombre:</strong>
          <%= @baby %>
        </p>
      </div>
      <div class="col-9 pt-3">
        <table class="shadow-lg p-2 mb-5 table table-bordered table-dark rounded" >
          <thead style="font-size:12px;">
            <tr>
              <th class="text-center">Veces que Tomo leche Hoy</th>
              <th class="text-center">Ultima vez que Tomo</th>
              <th class="text-center">Cuanto tiempo Tomo Hoy</th>
              <th class="text-center">Cantidad de Leche Tomada Hoy</th>
            </tr>
          </thead>

          <tbody style="font-size:10px;" >
              <tr>
                <td class="text-center" ><%= @baby.breast_feeding_times_today %></td>
                <% if @baby.last_time_drinking == ""%>
                  <td class="text-center" >Sin Registro</td>
                <% else %>
                  <td class="text-center" ><%= @baby.last_time_drinking.strftime("%d-%m-%Y") %></td>
                <% end %>
                <td class="text-center" ><%= @baby.breast_feeding_duration_today %> Minutos.-</td>
                <td class="text-center" ><%= @baby.breast_feeding_quantity_today %> cc.-</td>
              </tr>
          </tbody>
        </table>
      </div>
    </div> 
  </div>
</div>

<div class="text-center m-4">
  <%= link_to 'Editar Bebe', edit_baby_path(@baby), class:"btn btn-dark rounded-pill border border-white btn-sm" %> |
  <%= link_to 'Home', babies_path, class:"btn btn-dark rounded-pill border border-white btn-sm" %> |
  <%= link_to 'Nuevo Registro', new_baby_breast_feeding_path(@baby), class:"btn btn-dark rounded-pill border border-white btn-sm" %>
</div>

<div class="text-center px-5 mb-5">
  <div class="container-fluid p-4 shadow-lg mb-2 border border-info rounded-pill" style="background:#84c760;">
    <h1 class="text-center text-white mb-3"  style="font-size:25px; text-shadow: 0.1em 0.1em 0.05em #333">Registros de Lactancia</h1>
    <div class="container">
       <table class="shadow-lg p-2 mb-5 table table-bordered table-dark rounded" >
          <thead style="font-size:15px;">
            <tr>
              <th class="text-center">Cantidad de Tiempo en Minutos</th>
              <th class="text-center">Total de CC Tomados</th>
              <th class="text-center">Fecha de Registro</th>
              <th colspan="3"></th>  
            </tr>
          </thead>

          <tbody style="font-size:13px;" >   
              <% @baby.breast_feedings.each do |breast_feeding| %>        
              <tr>
                <td><%= breast_feeding.duration %></td>
                <td><%= breast_feeding.quantity %></td> 
                <td><%= breast_feeding.created_at.strftime("%d-%m-%Y %H:%M") %></td> 
                <td><%= link_to 'Editar', edit_baby_breast_feeding_path(@baby, breast_feeding), class:"btn btn-success rounded-pill btn-sm" %></td>
                <td><%= link_to 'Eliminar', baby_breast_feeding_path(@baby, breast_feeding), method: :delete, data: { confirm: 'Estas Seguro?' }, class:"btn btn-danger rounded-pill btn-sm" %></td>       
              </tr>   
              <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/breast_feedings/_form.html.erb
<%= form_with(model: [@baby, breast_feeding], local: true) do |form| %>
  <% if breast_feeding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(breast_feeding.errors.count, "error") %> prohibited this breast_feeding from being saved:</h2>

      <ul>
      <% breast_feeding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-center">
    <div class="field">
      <%= form.label :duration, class:" text-white", style:"font-size:15px; text-shadow: 0.1em 0.1em 0.05em #333" %>
      <%= form.number_field :duration %>
    </div>

    <div class="field">
      <%= form.label :quantity, class:" text-white", style:"font-size:15px; text-shadow: 0.1em 0.1em 0.05em #333" %>
      <%= form.number_field :quantity %>
    </div>

    <div class="actions mt-4">
      <%= form.submit class:"btn btn-primary rounded-pill border border-white" %>
    </div>
  </div>
<% end %>

app/views/breast_feedings/edit.html.erb
<div class="container">
    <div class="container-fluid p-4 shadow-lg mb-2 border border-info rounded-pill" style="background:#84c760;">
        <h1 class="text-center text-white mb-3"  style="font-size:25px; text-shadow: 0.1em 0.1em 0.05em #333">Editando Lactancia</h1>
        <div class="m-3">
            <%= render 'form', breast_feeding: @breast_feeding %>
        </div>
    </div>
   
    <div class="text-center m-5">
        <%= link_to 'Volver', baby_path(@baby), class:"btn btn-dark rounded-pill border border-white btn-sm" %>    
    </div>    
</div>

app/views/breast_feedings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Breast Feedings</h1>

<table>
  <thead>
    <tr>
      <th>Duration</th>
      <th>Quantity</th>
      <th>Baby</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breast_feedings.each do |breast_feeding| %>
      <tr>
        <td><%= breast_feeding.duration %></td>
        <td><%= breast_feeding.quantity %></td>
        <td><%= breast_feeding.baby %></td>
        <td><%= link_to 'Show', breast_feeding %></td>
        <td><%= link_to 'Edit', edit_breast_feeding_path(breast_feeding) %></td>
        <td><%= link_to 'Destroy', breast_feeding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breast Feeding', new_breast_feeding_path %>

app/views/breast_feedings/new.html.erb
<div class="container">
    <div class="container-fluid p-4 shadow-lg mb-2 border border-info rounded-pill" style="background:#84c760;">
        <h1 class="text-center text-white mb-3"  style="font-size:25px; text-shadow: 0.1em 0.1em 0.05em #333">Nueva Lactancia</h1>
        <div class="m-3">
            <%= render 'form', breast_feeding: @breast_feeding %>
        </div>
    </div>
   
    <div class="text-center m-5">
        <%= link_to 'Volver', baby_path(@baby), class:"btn btn-dark rounded-pill border border-white btn-sm" %>    
    </div>    
</div>

app/views/breast_feedings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Duration:</strong>
  <%= @breast_feeding.duration %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @breast_feeding.quantity %>
</p>

<p>
  <strong>Baby:</strong>
  <%= @breast_feeding.baby %>
</p>

<%= link_to 'Edit', edit_breast_feeding_path(@breast_feeding) %> |
<%= link_to 'Back', breast_feedings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio Esposa Apu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- Fonts Awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.1/css/all.css" integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q" crossorigin="anonymous">
    <!--Fonts Google-->
    <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&display=swap" rel="stylesheet">
    <!--Hoja de Estilos-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--JavaScrip-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Librerias Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>

  <body style="font-family: 'Rock Salt', cursive; background:#fed521;">
    <nav class="shadow-lg p-1 mb-5  rounded" style="background:#2fa7cc;">
      <div class="container navbar navbar-dark">
        <%= image_tag 'https://www.mediagroup.mx/wp-content/uploads/2018/04/Apu_Nahasapeemapetilon_2.png', class: 'navbar-brand', style: 'width: 100px;' %>
        <%= link_to "Desafio La Esposa de Apu", root_path, class:"navbar-brand font-weight-bold", style:"font-size:40px; text-shadow: 0.1em 0.1em 0.05em #333" %>
        <%= image_tag 'https://vignette.wikia.nocookie.net/lossimpson/images/2/28/Manjula_Nahasapeemapetilon.png/revision/latest/top-crop/width/360/height/450?cb=20140702115631&path-prefix=es', class: 'navbar-brand', style: 'width: 80px;' %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>